# GitHub Action for eeg-workflows to run type checking, linting and tests
name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  types:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout current branch'
        uses: actions/checkout@v2

      - name: 'Setup Python 3.8.8'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'

      - name: 'Install dependencies'
        run: pip install -r requirements-dev.txt

      - name: 'Run type checker'
        run: make test-types

  linting:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout current branch'
        uses: actions/checkout@v2

      - name: 'Setup Python 3.8.8'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'

      - name: 'Install dependencies'
        run: pip install -r requirements-dev.txt

      - name: 'Run flake8'
        run: make test-linting

  units:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout current branch'
        uses: actions/checkout@v2

      - name: 'Setup Python 3.8.8'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'

      - name: 'Install dependencies'
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: 'Run unit tests'
        run: make test-units
